### ISSUE TITLE
Issue with python loader

### ISSUE THREAD

**Issue by MCherrey** [fossfreedom/coverart-search-providers#24]
Hello, I am unable to enable the plugin. (Manjaro 16.06.1) It seems to be an issue with the python plugin loader. Here is my terminal output:

```
(rhythmbox:19430): Rhythmbox-WARNING **: Unable to start mDNS browsing: MDNS service is not running

(rhythmbox:19430): libdmapsharing-WARNING **: Unable to initialize mDNS: Daemon not running

(rhythmbox:19430): libdmapsharing-WARNING **: Unable to notify network of media sharing: The avahi MDNS service is not running
/usr/lib/rhythmbox/plugins/equalizer/Conf.py:20: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf, Gst
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/equalizer/equalizer.py", line 38, in do_activate
    self.eq = Gst.ElementFactory.make('equalizer-10bands', None)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 217, in make
    return Gst.ElementFactory.make(factory_name, instance_name)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 348, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer
```

This is were I enabled the plugin:

```
(rhythmbox:19430): libpeas-WARNING **: The 'python' plugin loader has not been enabled

(rhythmbox:19430): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed

(rhythmbox:19430): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed
```

This issue also effects the coverart browser plugin, since I cannot use that plugin without enabling this one. Also your AUR link on the main page does not work.
##

**Comment by fossfreedom** [comment]
the error reported is due to the equalizer plugin you are attempting to load - not this plugin.

**Comment by MCherrey** [comment]
I am not talking about the first part of the code. The second part happens specifically when I enable this plugin. Here is my terminal ouput without the equalizer plugin enabled.

```
(rhythmbox:25050): Rhythmbox-WARNING **: Unable to start mDNS browsing: MDNS service is not running

(rhythmbox:25050): libdmapsharing-WARNING **: Unable to initialize mDNS: Daemon not running

(rhythmbox:25050): libdmapsharing-WARNING **: Unable to notify network of media sharing: The avahi MDNS service is not running

#I enable the plugin at this moment

(rhythmbox:25050): libpeas-WARNING **: The 'python' plugin loader has not been enabled

(rhythmbox:25050): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed

(rhythmbox:25050): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed
```

I get the exact message when I enable the plugin.

**Comment by fossfreedom** [comment]
k - that second error message says it is trying load the python version of the plugin - it should be loading python3

did you install ./install --rb2 ?

RB3 instructions say to use ./install

**Comment by MCherrey** [comment]
Alright, when I reinstalled it, that problem was fixed. Now when I try to open the preferences it gives me this.

```
(rhythmbox:26640): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/coverart-search-providers/coverart_search_providers_prefs.py", line 200, in do_create_configure_widget
    return self._create_display_contents(self)
  File "/usr/lib/rhythmbox/plugins/coverart-search-providers/coverart_search_providers_prefs.py", line 265, in _create_display_contents
    builder.add_from_file(rb.find_plugin_file(plugin, "ui/coverart_search_providers_prefs.ui"))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:26640): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
```

Also I do not see any functionality in the UI that indicates that the plugin is working.
